import { Link } from "wouter";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { ChevronDown } from "lucide-react";
import { Badge } from "@/components/ui/badge";

const mockReports = [
  { id: "HR-001", reportName: "Weekly Harvest Summary", period: "Week 11 2024", generatedBy: "John Smith", generatedDate: "2024-03-15", format: "PDF", status: "Available" },
  { id: "HR-002", reportName: "Quality Analysis Report", period: "March 2024", generatedBy: "Sarah Johnson", generatedDate: "2024-03-14", format: "Excel", status: "Available" },
  { id: "HR-003", reportName: "Farmer Performance Report", period: "Q1 2024", generatedBy: "Mike Davis", generatedDate: "2024-03-13", format: "PDF", status: "Available" },
  { id: "HR-004", reportName: "Harvest Cost Analysis", period: "March 2024", generatedBy: "Tom Wilson", generatedDate: "2024-03-12", format: "Excel", status: "Processing" },
  { id: "HR-005", reportName: "Regional Comparison Report", period: "Q1 2024", generatedBy: "Lisa Brown", generatedDate: "2024-03-11", format: "PDF", status: "Available" },
];

export default function HarvestReports() {
  return (
    <div className="space-y-4 -m-6">
      <div className="px-6 pt-6 flex items-center justify-between">
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="/harvests" data-testid="breadcrumb-harvests">Harvests</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage className="font-medium" data-testid="breadcrumb-current">Reports</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
        
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="default" data-testid="button-actions">
              Actions
              <ChevronDown className="ml-2 h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem data-testid="menu-generate-report">Generate Report</DropdownMenuItem>
            <DropdownMenuItem data-testid="menu-schedule-report">Schedule Report</DropdownMenuItem>
            <DropdownMenuItem data-testid="menu-view-templates">View Templates</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <div className="border-t">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report ID</TableHead>
              <TableHead>Report Name</TableHead>
              <TableHead>Period</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Generated Date</TableHead>
              <TableHead>Format</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="w-[50px]"></TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {mockReports.map((report, index) => (
              <TableRow key={report.id} className="hover:bg-muted/30" data-testid={`row-report-${index}`}>
                <TableCell className="font-medium">
                  <Link href={`/harvest-reports/${report.id}`} data-testid={`link-report-${index}`}>
                    <span className="text-primary hover:underline cursor-pointer">{report.id}</span>
                  </Link>
                </TableCell>
                <TableCell data-testid={`text-report-name-${index}`}>{report.reportName}</TableCell>
                <TableCell data-testid={`text-period-${index}`}>{report.period}</TableCell>
                <TableCell>
                  <Link href={`/users/${report.generatedBy}`} data-testid={`link-generated-by-${index}`}>
                    <span className="text-sm hover:underline cursor-pointer">{report.generatedBy}</span>
                  </Link>
                </TableCell>
                <TableCell data-testid={`text-generated-date-${index}`}>{report.generatedDate}</TableCell>
                <TableCell>
                  <Badge variant="secondary" className="text-xs" data-testid={`badge-format-${index}`}>{report.format}</Badge>
                </TableCell>
                <TableCell>
                  <Badge variant={report.status === "Available" ? "secondary" : "outline"} className="text-xs" data-testid={`badge-status-${index}`}>
                    {report.status}
                  </Badge>
                </TableCell>
                <TableCell>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon" data-testid={`button-actions-${index}`}>
                        <ChevronDown className="h-4 w-4" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuItem data-testid={`menu-download-${index}`}>Download</DropdownMenuItem>
                      <DropdownMenuItem data-testid={`menu-view-${index}`}>View Report</DropdownMenuItem>
                      <DropdownMenuItem data-testid={`menu-share-${index}`}>Share</DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
